"""empty message

Revision ID: fa209e78e2e6
Revises: 
Create Date: 2020-09-15 23:45:49.263648

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa
from app import db

# revision identifiers, used by Alembic.
from app.models.cliente_models import Cliente

revision = 'fa209e78e2e6'
down_revision = None
branch_labels = None
depends_on = None

db.create_all()

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('data_nascimento', sa.DateTime(), nullable=True),
    sa.Column('profissao', sa.String(length=30), nullable=True),
    sa.Column('sexo', sqlalchemy_utils.types.choice.ChoiceType(Cliente.SEXO_CHOICES), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clientes')
    # ### end Alembic commands ###
